trigger:
  branches:
    include:
      - feature/terraform-infra

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: azurerm
    command: init
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent/preprod'

- task: TerraformTaskV4@4
  displayName: Terraform Validate
  inputs:
    provider: azurerm
    command: validate
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent/preprod'

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: azurerm
    command: plan
    workingDirectory: '$(System.DefaultWorkingDirectory)/parent/preprod'